feat: 옷 추가 팝업 생성
KWEBofficial/stylevillage-client pull request #14
Opened 2024-01-17 08:06 UTC by SJBae1

옷 추가하기 팝업 생성했습니다.

Post가 제대로 되지 않아서 계속 찾는 중입니다ㅠ (입력하고 등록 버튼 누르면 post에서 error가 나서 handlesubmit 내에서 catch문으로 빠져 "옷 등록에 실패하였습니다." 스낵바가 뜹니다)
옷장 정보 찾는 것도 이전에 오류가 있어서 우선 closet도 제외하고 PR 올렸습니다.

![1](https://github.com/KWEBofficial/stylevillage-client/assets/145450139/c51801c6-6842-4afc-8f02-a14e31c92674)

2024-01-17 13:18 UTC, readygetset commented
복잡한 태스크인데 수고 많으셨습니다! 다만 수정도 가능하게 해야 해서 value를 props으로 받아서 default value로 반영하는 코드도 있어야 할 거 같네요! 넘어온 props가 있는지 여부에 따라 default value를 다르게 해야 할 거 같습니당

2024-01-18 07:55 UTC, SJBae1 commented
post는 해결되어 DB에 생성되고, 옷장 고르는게 해결이 안돼서 우선 수정하기부터 추가해보겠습니다.
지금은 옷장 고를 수 없고, 전체 옷장에 들어가도록(closet = null) 설정해두었습니다.

2024-01-18 09:15 UTC, SJBae1 commented
value={null}로 하면 추가, value=closetdata로 하면 수정하도록 기존값으로 초기화되도록 해두었습니다
수정은 과외있어서 PR 급하게 올리느라 확인을 못해서 로직상 문제는 없는 것 같은데 확인 한번만 부탁드릴게요!
pages/Main에 있는 아래 코드랑 return문 가장 아래부분 확인하셔서 사용하시면 될 것 같습니다.
const [open, setOpen] = useState(false);
const handleOpen = () => {
    setOpen(true);
  };
 const handleClose = () => {
    setOpen(false);
  };
 옷장 로직이 해결이 안되어서 우선 전체옷장으로 들어가게(null값 고정) 해두었는데 다녀와서 PR 확인하고 밤에 가능하면 고쳐보겠습니다

2024-01-18 09:21 UTC, readygetset requested changes

2024-01-18 09:21 UTC, readygetset commented on src/components/AddClothesPopUp/index.tsx
> +        const isPosted = await postClothesAPICall({ clothes, token });
수정이 도입되면 post인지 put인지 구분하는 로직 필요하지 않나요? values? 수정 : 생성 으로 하면 될 거 같긴 합니다

2024-01-18 20:24 UTC, SJBae1 commented
옷장 선택 및 추가/수정 고를 수 있게 변경하였습니다. 추가, 수정 모두 테스트 완료했습니다.
컴포넌트에 AddClothesBtn 추가해뒀고 주석으로 간단히 요약해두었으니 참고하셔서 사용하시면 좋을 것 같습니다!

2024-01-19 06:38 UTC, merged