feat: add main page
KWEBofficial/stylevillage-client pull request #6
Opened 2024-01-14 18:17 UTC by isseul

메인 페이지의 상단 요소들을 구현했습니다.
검색 API가 아직 완성되지 않아서 api가 제대로 작동하는지 테스트해보지는 못했습니다.

현재 페이지 모습입니다. 
![image](https://github.com/KWEBofficial/stylevillage-client/assets/129672066/5f7c6a65-eb44-4dd2-87cb-5487c793add4)

아래 컴포넌트를 만들었습니다.
1. Chip
2. CategoryChips
3. SearchBar

해결 못했거나 궁금한 부분입니다.
디자인 관련
1. 검색 입력란 안에 버튼을 깔끔하게 넣는 방법을 모르겠습니다.
2. 버튼과 textfield에 기본으로 들어가 있는 설정을 없앨 수 있는지 궁금합니다.
3. textfiled의 border가 변경이 안되던데 아예 변경할 수 있는 방법이 없는 건가요?

기능 관련
5. 검색 결과를 session에 저장하는 게 맞나요?
6. 저희가 검색 구현을 body로 받아서 하기로 했으니까 query는 안 건드려도 되는 거 맞나요?

추가로 검색 api에 대여가능 필터도 추가해야 할 것 같습니다.

2024-01-15 00:40 UTC, readygetset commented on src/components/SearchBar/index.tsx
> +        <Button
IconButton 쓰시면 깔끔하게 될겁니당

2024-01-15 00:43 UTC, readygetset commented
설정 바꿀 수는 있는데 좀 번거로워서 안 했어요 ㅎㅎ.. 그냥 sx 안에서 최대한 바꿔보시는 게 나을 거 같습니당.. textfield도 그냥 borderRadius 안 주고 네모나게 해도 괜찮아요

2024-01-15 01:13 UTC, readygetset commented
그리고 디자인 면에서 피그마처럼 배경색이 칩 선택했을 때 색보다 더 연한 색이었으면 좋겠습니다

2024-01-15 01:16 UTC, readygetset requested changes

2024-01-15 01:16 UTC, readygetset commented on src/components/CategoryChips/index.tsx
> +    props.onClickHandler(props.category, label, isSelected);
이거랑 chip의 handleClick은 다른 기능인건가요?

2024-01-15 01:16 UTC, readygetset commented on src/components/Chip/index.tsx
> +        fontWeight: 'bold',
겹치는 게 많아서 fontSize: isSelected? black : white 이런 식으로 하는 게 나을 거 같습니다

2024-01-15 01:16 UTC, readygetset commented on src/hooks/api/search/search.ts
> +  // filter 추가해야 함.
앞으로 해야할 일은 /* TODO: ~*/ 이렇게 써주시면 한 눈에 들어오고 좋을 거 같습니다.

2024-01-15 01:16 UTC, readygetset commented on src/pages/Main/index.tsx
> +      <SearchBar searchKeyWord={''} categorySelected={[]} seasonSelected={[]} />
여기서 props로 뭘 하는 게 없어보이는데 왜 넘기는 건가요?

2024-01-15 01:16 UTC, readygetset commented on src/hooks/api/search/search.ts
> +    const response = await axios.post(`${process.env.REACT_APP_API_URL}/search/`, values);
post 아니고 get이어야 할 거 같습니다. 이거 잘 되는지 테스트해주세요. 개발자 도구 네트워크 탭에서 확인해주시면 됩니다.

2024-01-15 08:11 UTC, isseul commented on src/pages/Main/index.tsx
> +      <SearchBar searchKeyWord={''} categorySelected={[]} seasonSelected={[]} />
검색 페이지에서 search바를 쓸 때는 저 정보가 있어야 검색어나 칩 선택 여부 등을 유지할 수 있을 것 같아서 searchBar의 props를 정의했습니다.
interface에서는 default 값 설정을 못하길래 메인페이지에서는 검색어, 선택된 칩 모두 공백으로 전달하도록 했습니다.

2024-01-15 12:04 UTC, readygetset commented on src/pages/Main/index.tsx
> +      <SearchBar searchKeyWord={''} categorySelected={[]} seasonSelected={[]} />
아 넵넵 좋습니다

2024-01-16 08:45 UTC, readygetset approved these changes

2024-01-16 13:37 UTC, merged